apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    alb.ingress.kubernetes.io/scheme: internet-facing  # Use "internal" for internal ALB
  labels:
    app: {{ .Release.Name }}-2048
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-2048
