replicaCount: 1

image:
  repository: palakuws/2048game
  tag: 12
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
